/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sun.star.wizards.ui;

import com.sun.star.wizards.calendar.Manager;
import com.sun.star.wizards.calendar.NumDiaDeSemana;
import com.sun.star.wizards.calendar.RepitPersonalizado;
import com.sun.star.wizards.calendar.RepitPersonalizadoAnualPorDia;
import com.sun.star.wizards.calendar.RepitPersonalizadoAnualPorNumDia;
import com.sun.star.wizards.calendar.RepitPersonalizadoDiario;
import com.sun.star.wizards.calendar.RepitPersonalizadoMensual;
import com.sun.star.wizards.calendar.RepitPersonalizadoSemanal;
import java.awt.Point;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author adrivero
 */
public class PersRepitForm extends javax.swing.JDialog {

    /**
     * Creates new form EditDate
     */
    private RepitPersonalizado personalizado;
    Calendar cal;
    Manager man;

    public PersRepitForm(java.awt.Frame parent, boolean modal, RepitPersonalizado personalizado, Calendar cale, Point com, Manager man) {
        super(parent, modal);
        initComponents();
        setLocation(com);
        this.personalizado = personalizado;
        if (this.personalizado == null) {
            this.personalizado = new RepitPersonalizadoDiario(false, 1, 10, cale, 0);
        }
        this.cal = cale;
        this.man = man;
        iniciaComponets();
        CargaLosDatosPersonalizados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioSinFechaFin = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadiofechaFin = new javax.swing.JRadioButton();
        jRadioCantRepit = new javax.swing.JRadioButton();
        jSpinnerCantRepit = new javax.swing.JSpinner();
        jDateChooFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComgoRepit = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioCada = new javax.swing.JRadioButton();
        jSpinnerCadaSalto = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanelAnual = new javax.swing.JPanel();
        jComboBoxAnualNumDia = new javax.swing.JComboBox();
        jRadioAnualDia = new javax.swing.JRadioButton();
        jRadioAnualNumDia = new javax.swing.JRadioButton();
        jSpinnerAnualdia = new javax.swing.JSpinner();
        jMonthChooserAnualDia = new com.toedter.calendar.JMonthChooser();
        jMonthChooserAnualNumDia = new com.toedter.calendar.JMonthChooser();
        jComboBoxAnualDiaSem = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelSemanal = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanelMensual = new javax.swing.JPanel();
        jComboBoxNumDiaSem = new javax.swing.JComboBox();
        jComboBoxDiaSem = new javax.swing.JComboBox();
        jPanelDiario = new javax.swing.JPanel();
        jRadiolaborable = new javax.swing.JRadioButton();

        setTitle("Personalizar repetición");
        setBackground(new java.awt.Color(200, 221, 242));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(200, 221, 242));
        jPanel5.setPreferredSize(new java.awt.Dimension(349, 479));

        jPanel3.setBackground(new java.awt.Color(200, 221, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jRadioSinFechaFin);
        jRadioSinFechaFin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioSinFechaFin.setText("Sin fecha final");
        jRadioSinFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSinFechaFinActionPerformed(evt);
            }
        });

        jLabel3.setText("Rango de repetición:");

        buttonGroup1.add(jRadiofechaFin);
        jRadiofechaFin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadiofechaFin.setText("Repetir hasta");
        jRadiofechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadiofechaFinActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioCantRepit);
        jRadioCantRepit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioCantRepit.setText("Crear");
        jRadioCantRepit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCantRepitActionPerformed(evt);
            }
        });

        jSpinnerCantRepit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerCantRepit.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));

        jDateChooFechaFin.setToolTipText("Introducir fecha");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("instancia(s)");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSpinnerCantRepit, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel6, org.jdesktop.beansbinding.BeanProperty.create("enabled"), "");
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioSinFechaFin)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioCantRepit)
                                    .addComponent(jRadiofechaFin))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jSpinnerCantRepit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jDateChooFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jRadioSinFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioCantRepit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCantRepit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadiofechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sun/star/wizards/calendar/Images/20-check.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sun/star/wizards/calendar/Images/delete-24.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(200, 221, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Patrón de repetición:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Repetir:");

        jComgoRepit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComgoRepit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diariamente", "Semanalmente", "Mensualmente", "Anualmente" }));
        jComgoRepit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComgoRepitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(200, 221, 242));

        jPanel2.setBackground(new java.awt.Color(200, 221, 242));

        buttonGroup2.add(jRadioCada);
        jRadioCada.setText("Cada");
        jRadioCada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCadaActionPerformed(evt);
            }
        });

        jSpinnerCadaSalto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerCadaSalto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel7, org.jdesktop.beansbinding.ELProperty.create("${text}"), jSpinnerCadaSalto, org.jdesktop.beansbinding.BeanProperty.create("toolTipText"));
        bindingGroup.addBinding(binding);

        jLabel7.setText("día(s)");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSpinnerCadaSalto, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel7, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioCada, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerCadaSalto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioCada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSpinnerCadaSalto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelAnual.setBackground(new java.awt.Color(200, 221, 242));

        jComboBoxAnualNumDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup3.add(jRadioAnualDia);
        jRadioAnualDia.setSelected(true);
        jRadioAnualDia.setText("El:");
        jRadioAnualDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAnualDiaActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioAnualNumDia);
        jRadioAnualNumDia.setText("El:");
        jRadioAnualNumDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAnualNumDiaActionPerformed(evt);
            }
        });

        jSpinnerAnualdia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerAnualdia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jComboBoxAnualDiaSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("De:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("De:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanelAnualLayout = new javax.swing.GroupLayout(jPanelAnual);
        jPanelAnual.setLayout(jPanelAnualLayout);
        jPanelAnualLayout.setHorizontalGroup(
            jPanelAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioAnualNumDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioAnualDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnualLayout.createSequentialGroup()
                        .addComponent(jSpinnerAnualdia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthChooserAnualDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAnualLayout.createSequentialGroup()
                        .addComponent(jComboBoxAnualNumDia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAnualDiaSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jMonthChooserAnualNumDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelAnualLayout.setVerticalGroup(
            jPanelAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioAnualDia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jSpinnerAnualdia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jMonthChooserAnualDia, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioAnualNumDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAnualNumDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAnualDiaSem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jMonthChooserAnualNumDia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanelAnual);
        jPanelAnual.setBounds(0, 0, 300, 130);

        jPanelSemanal.setBackground(new java.awt.Color(200, 221, 242));

        jCheckBox2.setText("mm");

        jCheckBox1.setText("mm");

        jCheckBox3.setText("mm");

        jCheckBox4.setText("mm");

        jCheckBox5.setText("mm");

        jCheckBox6.setText("mm");

        jCheckBox7.setText("mm");

        javax.swing.GroupLayout jPanelSemanalLayout = new javax.swing.GroupLayout(jPanelSemanal);
        jPanelSemanal.setLayout(jPanelSemanalLayout);
        jPanelSemanalLayout.setHorizontalGroup(
            jPanelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSemanalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSemanalLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelSemanalLayout.createSequentialGroup()
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addGap(116, 116, 116))))
        );
        jPanelSemanalLayout.setVerticalGroup(
            jPanelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSemanalLayout.createSequentialGroup()
                .addGroup(jPanelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox5))
                .addGap(0, 84, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanelSemanal);
        jPanelSemanal.setBounds(0, 0, 300, 130);

        jPanelMensual.setBackground(new java.awt.Color(200, 221, 242));

        jComboBoxNumDiaSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxDiaSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelMensualLayout = new javax.swing.GroupLayout(jPanelMensual);
        jPanelMensual.setLayout(jPanelMensualLayout);
        jPanelMensualLayout.setHorizontalGroup(
            jPanelMensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensualLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jComboBoxNumDiaSem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDiaSem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelMensualLayout.setVerticalGroup(
            jPanelMensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNumDiaSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDiaSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanelMensual);
        jPanelMensual.setBounds(0, 0, 300, 130);

        jPanelDiario.setBackground(new java.awt.Color(200, 221, 242));

        buttonGroup2.add(jRadiolaborable);
        jRadiolaborable.setText("Solo días Laborables");
        jRadiolaborable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadiolaborableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDiarioLayout = new javax.swing.GroupLayout(jPanelDiario);
        jPanelDiario.setLayout(jPanelDiarioLayout);
        jPanelDiarioLayout.setHorizontalGroup(
            jPanelDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadiolaborable)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanelDiarioLayout.setVerticalGroup(
            jPanelDiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadiolaborable)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanelDiario);
        jPanelDiario.setBounds(0, 0, 300, 130);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComgoRepit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 117, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComgoRepit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
          
            if ( cal.after(jDateChooFechaFin.getCalendar())) {
                JOptionPane.showMessageDialog(this, "La fecha final de la repectición"
                        + " no debe ser menor que la fecha inicial de la tarea.", "Error", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/com/sun/star/wizards/calendar/Images/info.png")));
            }else{

            Calendar cal1 = (Calendar) cal.clone();
            cal = jDateChooFechaFin.getCalendar();
            int sel = jComgoRepit.getSelectedIndex();
            int cantrepit = Integer.parseInt(jSpinnerCantRepit.getValue().toString());
            int repitcada = Integer.parseInt(jSpinnerCadaSalto.getValue().toString());
            int conFinal = -1;
            if (jRadioSinFechaFin.isSelected()) {
                conFinal = 0;
            } else if (jRadioCantRepit.isSelected()) {
                conFinal = 1;
            } else if (jRadiofechaFin.isSelected()) {
                conFinal = 2;

            }
          
                Calendar hasta = jDateChooFechaFin.getCalendar();
                hasta.set(hasta.get(Calendar.YEAR), hasta.get(Calendar.MONTH), hasta.get(Calendar.DATE), 23, 59);
                switch (sel) {
                    case 0://diario
                        personalizado = new RepitPersonalizadoDiario(jRadiolaborable.isSelected(), repitcada, cantrepit, hasta, conFinal);
                        break;
                    case 1: //semanal;
                        boolean[] arr = new boolean[jPanelSemanal.getComponentCount()];
                        for (int i = 0; i < jPanelSemanal.getComponentCount(); i++) {
                            JCheckBox name = (JCheckBox) jPanelSemanal.getComponent(i);
                            arr[i] = name.isSelected();
                        }
                        personalizado = new RepitPersonalizadoSemanal(arr, repitcada, cantrepit, hasta, conFinal);
                        break;
                    case 2: //mensual
                        personalizado = new RepitPersonalizadoMensual((NumDiaDeSemana) jComboBoxNumDiaSem.getSelectedItem(),
                                (String) jComboBoxDiaSem.getSelectedItem(), repitcada, cantrepit, hasta, conFinal);
                        break;
                    case 3: //anual poniendo dia
                        if (jRadioAnualDia.isSelected()) {
                            int repitElDia = Integer.parseInt(jSpinnerAnualdia.getValue().toString());
                            personalizado = new RepitPersonalizadoAnualPorDia(repitElDia, jMonthChooserAnualDia.getMonth(), repitcada, cantrepit, hasta, conFinal);
                        } else { //anual poniendo num dia (primero seg....)
                            personalizado = new RepitPersonalizadoAnualPorNumDia(jMonthChooserAnualNumDia.getMonth(),
                                    (NumDiaDeSemana) jComboBoxAnualNumDia.getSelectedItem(),
                                    (String) jComboBoxAnualDiaSem.getSelectedItem(), repitcada, cantrepit, hasta, conFinal);
                        }
                        break;
                }

                this.dispose();
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Por favor verifique los campos", "Error", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/com/sun/star/wizards/calendar/Images/info.png")));

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        personalizado = null;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComgoRepitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComgoRepitActionPerformed
        ActualizaFramePatron();
    }//GEN-LAST:event_jComgoRepitActionPerformed

    private void jRadioAnualDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAnualDiaActionPerformed
        ActualizaFramePatron();
    }//GEN-LAST:event_jRadioAnualDiaActionPerformed

    private void jRadioAnualNumDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAnualNumDiaActionPerformed
        ActualizaFramePatron();
    }//GEN-LAST:event_jRadioAnualNumDiaActionPerformed

    private void jRadiolaborableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadiolaborableActionPerformed
        ActualizaFramePatron();
    }//GEN-LAST:event_jRadiolaborableActionPerformed

    private void jRadioCadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCadaActionPerformed
        ActualizaFramePatron();
    }//GEN-LAST:event_jRadioCadaActionPerformed

    private void jRadioSinFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSinFechaFinActionPerformed
        ActualizaFramePatron();
    }//GEN-LAST:event_jRadioSinFechaFinActionPerformed

    private void jRadioCantRepitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCantRepitActionPerformed
        ActualizaFramePatron();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCantRepitActionPerformed

    private void jRadiofechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadiofechaFinActionPerformed
        ActualizaFramePatron();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadiofechaFinActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBoxAnualDiaSem;
    private javax.swing.JComboBox jComboBoxAnualNumDia;
    private javax.swing.JComboBox jComboBoxDiaSem;
    private javax.swing.JComboBox jComboBoxNumDiaSem;
    private javax.swing.JComboBox jComgoRepit;
    private com.toedter.calendar.JDateChooser jDateChooFechaFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane2;
    private com.toedter.calendar.JMonthChooser jMonthChooserAnualDia;
    private com.toedter.calendar.JMonthChooser jMonthChooserAnualNumDia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAnual;
    private javax.swing.JPanel jPanelDiario;
    private javax.swing.JPanel jPanelMensual;
    private javax.swing.JPanel jPanelSemanal;
    private javax.swing.JRadioButton jRadioAnualDia;
    private javax.swing.JRadioButton jRadioAnualNumDia;
    private javax.swing.JRadioButton jRadioCada;
    private javax.swing.JRadioButton jRadioCantRepit;
    private javax.swing.JRadioButton jRadioSinFechaFin;
    private javax.swing.JRadioButton jRadiofechaFin;
    private javax.swing.JRadioButton jRadiolaborable;
    private javax.swing.JSpinner jSpinnerAnualdia;
    private javax.swing.JSpinner jSpinnerCadaSalto;
    private javax.swing.JSpinner jSpinnerCantRepit;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public Calendar getCal() {
        return cal;
    }

    private void CargaLosDatosPersonalizados() {

        if (personalizado instanceof RepitPersonalizadoDiario) {
            jComgoRepit.setSelectedIndex(0);
            RepitPersonalizadoDiario personalizado1 = (RepitPersonalizadoDiario) personalizado;
            jRadiolaborable.setSelected(personalizado1.isSoloDiaLaborable());
            jRadioCada.setSelected(!personalizado1.isSoloDiaLaborable());
        } else {
            if (personalizado instanceof RepitPersonalizadoSemanal) {
                jComgoRepit.setSelectedIndex(1);
                RepitPersonalizadoSemanal personalizado1 = (RepitPersonalizadoSemanal) personalizado;
                String[] arr = man.getNamesCalendar(Calendar.DAY_OF_WEEK, Calendar.SHORT);
                for (int i = 0; i < arr.length; i++) {
                    JCheckBox name = (JCheckBox) jPanelSemanal.getComponent(i);
                    name.setSelected(personalizado1.getSelectedDay()[i]);

                }
            } else if (personalizado instanceof RepitPersonalizadoAnualPorDia) {
                jComgoRepit.setSelectedIndex(3);
                jRadioAnualDia.setSelected(true);
                RepitPersonalizadoAnualPorDia personalizado1 = (RepitPersonalizadoAnualPorDia) personalizado;
                jSpinnerAnualdia.setValue(personalizado1.getRepitElDia());
                jMonthChooserAnualDia.setMonth(personalizado1.getMounth());

            } else if (personalizado instanceof RepitPersonalizadoAnualPorNumDia) {
                jComgoRepit.setSelectedIndex(3);
                jRadioAnualNumDia.setSelected(true);
                RepitPersonalizadoAnualPorNumDia personalizado1 = (RepitPersonalizadoAnualPorNumDia) personalizado;
                jMonthChooserAnualNumDia.setMonth(personalizado1.getMounth());
                jComboBoxAnualNumDia.setSelectedItem(personalizado1.getNumDiaDeSemana());
                jComboBoxAnualDiaSem.setSelectedItem(personalizado1.getDiaDeSemana());

            } else if (personalizado instanceof RepitPersonalizadoMensual) {
                jComgoRepit.setSelectedIndex(2);
                RepitPersonalizadoMensual personalizado1 = (RepitPersonalizadoMensual) personalizado;
                jComboBoxNumDiaSem.setSelectedItem(personalizado1.getNumDiaDeSemana());
                jComboBoxDiaSem.setSelectedItem(personalizado1.getDiaDeSemana());

            }
            jRadioCada.setSelected(true);
        }
        ////////////////////////////
        jRadioSinFechaFin.setSelected(personalizado.getConFechaFinal() == 0);
        jRadioCantRepit.setSelected(personalizado.getConFechaFinal() == 1);
        jRadiofechaFin.setSelected(personalizado.getConFechaFinal() == 2);

        jSpinnerCantRepit.setValue(personalizado.getCantRepeticiones());
        jDateChooFechaFin.setCalendar(personalizado.getRepetirHastaDia());

        jSpinnerCadaSalto.setValue(personalizado.getRepitCada());

        ActualizaFramePatron();
    }

    private void ActualizaFramePatron() {
        int banderaPanel = jComgoRepit.getSelectedIndex();
        jPanelDiario.setVisible(banderaPanel == 0);
        jPanelSemanal.setVisible(banderaPanel == 1);
        jPanelMensual.setVisible(banderaPanel == 2);
        jPanelAnual.setVisible(banderaPanel == 3);
        jRadioCada.setSelected(banderaPanel != 0);
        String[] dd = {"día(s)", "semana(s)", "mes(es)", "año(s)"};
        jLabel7.setText(dd[banderaPanel]);
        jSpinnerCadaSalto.setEnabled(jRadioCada.isSelected());

        boolean banderaAnual = jRadioAnualDia.isSelected();
        jMonthChooserAnualDia.setEnabled(banderaAnual);
        jSpinnerAnualdia.setEnabled(banderaAnual);
        jLabel4.setEnabled(banderaAnual);
        jComboBoxAnualNumDia.setEnabled(!banderaAnual);
        jComboBoxAnualDiaSem.setEnabled(!banderaAnual);
        jMonthChooserAnualNumDia.setEnabled(!banderaAnual);
        jLabel5.setEnabled(!banderaAnual);
        boolean banderaRango = jRadioSinFechaFin.isSelected();
        jSpinnerCantRepit.setEnabled(!banderaRango && !jRadiofechaFin.isSelected());

        jDateChooFechaFin.setEnabled(!banderaRango && !jRadioCantRepit.isSelected());
    }

    private void iniciaComponets() {
        // el panel semanal
        // pongo los dias de la semana en los JCheckBox
        String[] arr = man.getNamesCalendar(Calendar.DAY_OF_WEEK, Calendar.SHORT);
        for (int i = 0; i < arr.length; i++) {
            JCheckBox name = (JCheckBox) jPanelSemanal.getComponent(i);
            name.setText(arr[i]);
        }
        // el panel mensual
        // pongo los numeros de los dias de la semana (primerom, segundo...)
        jComboBoxNumDiaSem.removeAllItems();
        for (NumDiaDeSemana dia : NumDiaDeSemana.values()) {
            jComboBoxNumDiaSem.addItem(dia);
        }
        jComboBoxDiaSem.removeAllItems();
        String[] arr1 = man.getNamesCalendar(Calendar.DAY_OF_WEEK, Calendar.LONG);
        for (String i : arr1) {
            jComboBoxDiaSem.addItem(i);
        }
        //panel anual
        jComboBoxAnualNumDia.removeAllItems();
        for (NumDiaDeSemana dia : NumDiaDeSemana.values()) {
            jComboBoxAnualNumDia.addItem(dia);
        }
        // pongo los dias de la semana en los JCheckBox
        jComboBoxAnualDiaSem.removeAllItems();
        arr1 = man.getNamesCalendar(Calendar.DAY_OF_WEEK, Calendar.LONG);
        for (String i : arr1) {
            jComboBoxAnualDiaSem.addItem(i);
        }

    }

    public RepitPersonalizado getPersonalizado() {
        return personalizado;
    }
}
